# All of the following recipes are my mother's recipes. A lot of the directions are in Hindi, so I'm just leaving them as such.
use NikeshProject;

# Kachoris
insert into Recipe values(1, 'Put 4 katoris of water and salt, then boil. Put oil in pan, saunf(saboot), Kalonji, jeera, heeng. mirchi and put tadka then put daal. Fry it a lot like aata. Then put garam masala - 1 spoon and dhania and Jeera powder - 1 spoon & mix Maida put oil and salt. Make small balls and fill with daal');
insert into Food values(1, 'Kachori', 'Snack', 'Indian', 300, 1);
insert into Mass values('1 katori', 100);
insert into Mass values('1/2 kg', 500);
insert into Mass values('2 kg', 2000);
insert into Ingredient values(1, 'Daal-Sabodtmoong', '1 katori');
insert into Ingredient values(2, 'Daal', '1/2 kg');
insert into Ingredient values(3, 'Maida', '2 kg');
insert into madeUpOf_areIn values(1, 1);
insert into madeUpOf_areIn values(1, 2);
insert into madeUpOf_areIn values(1, 3);

# Dil Khush Paneer Roll
insert into Recipe values(2, 'Put jeera, peas, ginger, chili, salt until cooked. Almond/Kaju - 1/2 kaju, kishmish & besan, chaat masala and fry. Filling ready. Hot water (warm) put paneer in it. After 12-15 minutes take it out and dry on cotton cloth and put filling and roll immediately and put long and seal and set in pan to serve. Fry butter, onion, ginger, garlic until golden then make gravy and leftover fillings and paneer crumbled. Put hot gravy on rolls and garam masala, coriander, and cream (2 big spoons) on top.');
insert into Food values(2, 'Dil Khush Paneer Roll', 'Snack', 'Indian', 200, 2);
insert into Mass values('500g', 500);
insert into Mass values('22', null);
insert into Mass values('20-22', null);
insert into Mass values('1 cup', 200);
insert into Mass values('2', null);
insert into Mass values('chopped', null);
insert into Mass values('1 tsp', null);
insert into Mass values('30-35', null);
insert into Mass values('1/2 cup', 100);
insert into Mass values('To taste', null);
insert into Mass values('', null);
insert into Mass values('100g', 100);
insert into Ingredient values(4, 'Paneer', '500g');
insert into Ingredient values(5, 'Almond and Kaju', '22');
insert into Ingredient values(6, 'Kishmish', '20-22');
insert into Ingredient values(7, 'Green Peas', '1 cup');
insert into Ingredient values(8, 'Chili', '2');
insert into Ingredient values(9, 'Ginger', 'chopped');
insert into Ingredient values(10, 'Coriander', 'chopped');
insert into Ingredient values(11, 'Besan - sauted', '1 tsp');
insert into Ingredient values(12, 'Long', '30-35');
insert into Ingredient values(13, 'Chaat masala', '1 tsp');
insert into Ingredient values(14, 'Jeera', '1 tsp');
insert into Ingredient values(15, 'Oil', '1/2 cup');
insert into Ingredient values(16, 'Salt', 'To taste');
insert into Ingredient values(17, 'Onion', '');
insert into Ingredient values(18, 'Garlic', '');
insert into Ingredient values(19, 'Sugar', '');
insert into Ingredient values(20, 'Deghi Mirch', '1 tsp');
insert into Ingredient values(21, 'Butter', '100g');
insert into Ingredient values(22, 'Tomato', '');
insert into Ingredient values(23, 'Haldi', '');
insert into madeUpOf_areIn values(2, 4);
insert into madeUpOf_areIn values(2, 5);
insert into madeUpOf_areIn values(2, 6);
insert into madeUpOf_areIn values(2, 7);
insert into madeUpOf_areIn values(2, 8);
insert into madeUpOf_areIn values(2, 9);
insert into madeUpOf_areIn values(2, 10);
insert into madeUpOf_areIn values(2, 11);
insert into madeUpOf_areIn values(2, 12);
insert into madeUpOf_areIn values(2, 13);
insert into madeUpOf_areIn values(2, 14);
insert into madeUpOf_areIn values(2, 15);
insert into madeUpOf_areIn values(2, 16);
insert into madeUpOf_areIn values(2, 17);
insert into madeUpOf_areIn values(2, 18);
insert into madeUpOf_areIn values(2, 19);
insert into madeUpOf_areIn values(2, 20);
insert into madeUpOf_areIn values(2, 21);
insert into madeUpOf_areIn values(2, 22);
insert into madeUpOf_areIn values(2, 23);

# Fruit Punch
insert into Recipe values(3, 'Mix all liquids with sugar. Add Welchs last and pour slowly. Stir well. Add ice ring and garnish with remainders');
insert into Drink values(1, 'Fruit Punch', 'F', 'Universal', 100, 3);
insert into Mass values('2 cans', 680);
insert into Mass values('2 bottles', null);
insert into Mass values('1', null);
insert into Mass values('24', null);
insert into Ingredient values(24, 'Orange Juice', '1/2 cup');
insert into Ingredient values(25, 'Grapefruit Juice', '1/2 cup');
insert into Ingredient values(26, 'Sugar', '1/2 cup');
insert into Ingredient values(27, 'Sprite Zero', '2 cans');
insert into Ingredient values(28, 'Sparkling whitegrape juice cocktail (Welchs)', '2 bottles');
insert into Ingredient values(29, 'Ice Ring', '1');
insert into Ingredient values(30, 'Orange thin slices', '1');
insert into Ingredient values(31, 'Seedless Red and Green Grapes (frozen)', '24');
insert into madeUpOf_areIn values(3, 24);
insert into madeUpOf_areIn values(3, 25);
insert into madeUpOf_areIn values(3, 26);
insert into madeUpOf_areIn values(3, 27);
insert into madeUpOf_areIn values(3, 28);
insert into madeUpOf_areIn values(3, 29);
insert into madeUpOf_areIn values(3, 30);
insert into madeUpOf_areIn values(3, 31);


# A Rob Roy (Scotch cocktail). Not my mother's recipe.'
insert into Recipe values(4, 'Shake whisky, vermouth, and bitters well with cracked ice, then strain into a chilled cocktail glass and garnish as you would a Manhattan, with a twist of lemon or, if you must, a cherry.');
insert into Drink values(2, 'Rob Roy (Scotch Cocktail)', 'T', 'Scottish', 145, 4);
insert into Mass values('2 oz', 57);
insert into Mass values('3/4 oz', 21);
insert into Mass values('1 dash', null);
insert into Ingredient values(32, 'Blended Scotch Whiskey', '2 oz');
insert into Ingredient values(33, 'Italian Vermouth', '3/4 oz');
insert into Ingredient values(34, 'Angostura bitter', '1 dash');
insert into madeUpOf_areIn values(4, 32);
insert into madeUpOf_areIn values(4, 33);
insert into madeUpOf_areIn values(4, 34);

# Now make a grocery list in which you buy all the supplies for all the recipes.
insert into GroceryList values(1, "2012-12-01");
insert into has_areIn values(1, 1);
insert into has_areIn values(2, 1);
insert into has_areIn values(3, 1);
insert into has_areIn values(4, 1);
insert into has_areIn values(5, 1);
insert into has_areIn values(6, 1);
insert into has_areIn values(7, 1);
insert into has_areIn values(8, 1);
insert into has_areIn values(9, 1);
insert into has_areIn values(10, 1);
insert into has_areIn values(11, 1);
insert into has_areIn values(12, 1);
insert into has_areIn values(13, 1);
insert into has_areIn values(14, 1);
insert into has_areIn values(15, 1);
insert into has_areIn values(16, 1);
insert into has_areIn values(17, 1);
insert into has_areIn values(18, 1);
insert into has_areIn values(19, 1);
insert into has_areIn values(20, 1);
insert into has_areIn values(21, 1);
insert into has_areIn values(22, 1);
insert into has_areIn values(23, 1);
insert into has_areIn values(24, 1);
insert into has_areIn values(25, 1);
insert into has_areIn values(26, 1);
insert into has_areIn values(27, 1);
insert into has_areIn values(28, 1);
insert into has_areIn values(29, 1);
insert into has_areIn values(30, 1);
insert into has_areIn values(31, 1);
insert into has_areIn values(32, 1);
insert into has_areIn values(33, 1);
insert into has_areIn values(34, 1);
